language: node_js
node_js:
  - "0.10"
python:
  - "2.7"
env:
  - TARGET=test
  - TARGET=test-browser
  - TARGET=test-generate-key
before_install:
  - sudo pip install -r requirements.txt --use-mirrors
script: npm run travis-$TARGET
