language: node_js
node_js:
  - "0.12"
  - "4"
python:
  - "2.7"
env:
  - CXX=g++-4.8
  - TARGET=test-main
  - TARGET=test-browser
  - TARGET=test-generate-key
before_install:
  - sudo pip install -r requirements.txt
script: npm run travis-$TARGET
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
